{% set name = "toytree" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eaton-lab/toytree/archive/{{ version }}.tar.gz
  sha256: 125f79ede5ed7ab49a2f79cfe63d360edfa77dec5d67db0c8155b3639b36a5d3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.10
    - toyplot >=0.17.0
    - requests
    - future

test:
  imports:
    - toytree

about:
  home: https://github.com/eaton-lab/toytree
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Minimalist tree plotting library using Toyplot.
  description: |
    A simple library for phylogenetic analyses in Python.
  doc_url: https://toytree.readthedocs.io/
  dev_url: https://github.com/eaton-lab/toytree

extra:
  recipe-maintainers:
    - eaton-lab
