{% set name = "toytree" %}
{% set version = "3.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eaton-lab/toytree/archive/{{ version }}.tar.gz
  sha256: 4de362b61d0b1717a26790cef16db80d8887532ce64906966dfb9cbd90cc1df5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy <2.0.0
    - scipy
    - pandas
    - toyplot >=1.0
    - requests
    - loguru
    - ghostscript

test:
  imports:
    - toytree

about:
  home: https://github.com/eaton-lab/toytree
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Tree visualization, manipulation, and evolutionary analysis library.
  description: |
    A simple library for tree visualization, manipulation, and evolutionary analysis in Python.
  doc_url: https://eaton-lab.org/toytree
  dev_url: https://github.com/eaton-lab/toytree

extra:
  recipe-maintainers:
    - eaton-lab
