{% set name = "toytree" %}
{% set version = "3.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eaton-lab/toytree/archive/{{ version }}.tar.gz
  sha256: daefcd8d1c768dadb781ab9100f2bc0c4bda22044ea6c9d5a2e07fba9075f7d2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - pandas
    - toyplot
    - requests
    - loguru
    - ghostscript

test:
  requires:
    - python {{ python_min }}
  imports:
    - toytree

about:
  home: https://github.com/eaton-lab/toytree
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Tree visualization, manipulation, and evolutionary analysis library.
  description: |
    A simple library for tree visualization, manipulation, and evolutionary analysis in Python.
  doc_url: https://eaton-lab.org/toytree
  dev_url: https://github.com/eaton-lab/toytree

extra:
  recipe-maintainers:
    - eaton-lab
