context:
  name: toytree
  version: "3.0.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/eaton-lab/toytree/archive/refs/tags/{{ version }}.tar.gz
  #url: https://github.com/eaton-lab/toytree/archive/{{ version }}.tar.gz
  sha256: 8495fa6ba849e9a94db302269976875849af376d785edffd96c94f81a532cd15

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - numpy
    - scipy
    - pandas
    - toyplot
    - requests
    - loguru
    - ghostscript

test:
  imports:
    - toytree
    pip_check: true

about:
  home: https://github.com/eaton-lab/toytree
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Tree visualization, manipulation, and evolutionary analysis library.
  description: |
    A simple library for tree visualization, manipulation, and evolutionary analysis in Python.
  doc_url: https://eaton-lab.org/toytree
  dev_url: https://github.com/eaton-lab/toytree

extra:
  recipe-maintainers:
    - eaton-lab
