{% set name = "toytree" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eaton-lab/toytree/archive/{{ version }}.tar.gz
  sha256: ce053b6e6f9688041c3ad1d3e21d71b9b5696d485a970ccef88a00f45448b0bc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.10
    - toyplot >=0.17.0
    - requests
    - future

test:
  imports:
    - toytree

about:
  home: https://github.com/eaton-lab/toytree
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Minimalist tree plotting library using Toyplot.
  description: |
    A simple library for phylogenetic analyses in Python.
  doc_url: https://toytree.readthedocs.io/
  dev_url: https://github.com/eaton-lab/toytree

extra:
  recipe-maintainers:
    - eaton-lab
