{% set name = "toytree" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eaton-lab/toytree/archive/{{ version }}.tar.gz
  sha256: 9e0fd6ba8af91cdd82c8f193c28224f5f6398dabc48ffed831ad26c1887455e2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.10
    - toyplot >=0.17.0
    - requests
    - future

test:
  imports:
    - toytree

about:
  home: https://github.com/eaton-lab/toytree
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Minimalist tree plotting library using Toyplot.
  description: |
    A simple library for phylogenetic analyses in Python.
  doc_url: https://toytree.readthedocs.io/
  dev_url: https://github.com/eaton-lab/toytree

extra:
  recipe-maintainers:
    - eaton-lab
